import {PageHero,SectionHeader,ServiceRows,IndustryPanels,Process,FAQSection,CTA} from '@/components/shared';
import {CustomerJourney} from '@/components/interactive';
import {pageMetadata} from '@/lib/site';
export const metadata=pageMetadata('Web Design, SEO & Paid Advertising Services','Choose the right marketing starting point for your real estate or home service business. Explore connected web design, SEO, Google Ads, and Meta Ads.','/services');
const choices=[
 ['People visit but do not inquire','Start by reviewing the website. Can visitors understand the service, find credible work, and take the next step? More traffic will not resolve an unclear page.'],
 ['The right people cannot find you','Review search visibility for your actual services and market. SEO can address technical barriers and content gaps; Google Ads can reach relevant existing demand.'],
 ['Advertising generates the wrong inquiries','Look at the offer, search terms or creative, landing page, and follow-up together. The useful question is where the message stops matching the customer you want.'],
 ['Customers need to see the work first','For a considered purchase, creative and evidence matter. Meta Ads can introduce the service, while the website supplies the detail a prospect needs to evaluate it.'],
];
export default function Services(){return <><PageHero label="Web design / SEO / Google Ads / Meta Ads" title={'FOUR DISCIPLINES.\nONE CLEAR DIRECTION.'} text="You do not need to choose a channel before understanding the problem. We connect web design, SEO, and paid advertising around the customers your real estate or home service business wants to reach." breadcrumb={[{name:'Services',href:'/services'}]}/>
 <section className="section container"><SectionHeader label="Where should you start?" title={'NAME THE PROBLEM.\nTHEN CHOOSE THE WORK.'}/><div className="scope-grid">{choices.map(([h,p])=><article key={h}><h3>{h}</h3><p>{p}</p></article>)}</div></section>
 <section className="section container"><SectionHeader label="The capabilities" title={'START WHERE IT MATTERS.\nCONNECT WHAT COMES NEXT.'}/><ServiceRows/></section><section className="section contrast-section"><div className="container"><SectionHeader label="The system" title={'FROM THE FIRST SEARCH\nTO THE FIRST CONVERSATION.'}/><CustomerJourney/></div></section><section className="section dark"><div className="container"><SectionHeader label="The markets" title={'BUILT FOR YOUR\nCUSTOMER’S DECISION.'}/><IndustryPanels/></div></section>
 <Process/><FAQSection title={'CHOOSING\nYOUR SERVICES.'} intro="How to decide what belongs in the first scope." items={[
 ['Do we have to hire you for all four services?','No. A project can focus on a website, SEO, Google Ads, or Meta Ads. We look at the surrounding customer journey so that the chosen service has a useful destination and a measurable purpose.'],
 ['What if we do not know which service we need?','Describe what is happening: too few inquiries, the wrong jobs, an outdated website, or advertising that is hard to assess. That context helps us identify what to review before recommending a scope.'],
 ['Should we fix the website before running ads?','If visitors cannot understand the offer or complete an inquiry, that needs attention. A full rebuild is not always necessary; a focused service page or landing page may be a more appropriate first step.'],
 ['How are priorities and costs decided?','The business goal, existing assets, technical requirements, and agreed deliverables determine the scope. Advertising spend is discussed separately from agency work.'],
 ]}/><CTA title={'LET’S FIND THE\nRIGHT STARTING POINT.'} text="Tell us where the customer journey is breaking down. You can describe the problem before deciding which services you need." label="Discuss Your Marketing Priorities"/></>;}
