import {PageHero,SectionHeader,Principles,IndustryPanels,Process,CTA,PrimaryButton} from '@/components/shared';
import {pageMetadata} from '@/lib/site';
export const metadata=pageMetadata('About Our Marketing Approach','Meet Digital Pathway’s approach to real estate and home service marketing: clear positioning, connected channels, useful measurement, and work you can explore.','/about');
export default function About(){return <><PageHero label="About Digital Pathway" title={'MARKETING WORKS BETTER\nWHEN EVERYTHING\nCONNECTS.'} text="We work with real estate and home service businesses that want their website, search presence, and advertising to support the same goal: a relevant customer conversation." breadcrumb={[{name:'About',href:'/about'}]}/>
 <section className="section container split-section"><div><p className="eyebrow">What we believe</p><h2>GOOD PIECES<br/>NEED A<br/>CLEAR PATH.</h2></div><div className="prose"><p className="large-copy">A beautiful website without traffic is incomplete. Traffic sent to a weak website loses its purpose.</p><p>SEO becomes more useful when it reflects how the business is positioned. Advertising becomes more coherent when the landing page carries the same intent. Measurement becomes more meaningful when it follows the customer decision.</p><p>Digital Pathway connects these pieces through web design, SEO, Google Ads, and Meta Ads. The goal is a clearer path from attention to a useful conversation.</p></div></section>
 <section className="section contrast-section"><div className="container"><SectionHeader label="How we think" title={'CLARITY FIRST.\nCONNECTION THROUGHOUT.'}/><Principles/></div></section>
 <section className="section dark"><div className="container"><SectionHeader label="Who we work with" title={'SPECIFIC MARKETS.\nA FOCUSED APPROACH.'}/><IndustryPanels/></div></section>
 <section className="section container split-section"><div><p className="eyebrow">Working together</p><h2>A CLEAR SCOPE.<br/>A SHARED DIRECTION.</h2></div><div className="prose"><p className="large-copy">You know the customers, jobs, and opportunities that matter to your business. That knowledge should shape the marketing.</p><p>We start by understanding the offer and the current customer journey. From there, we define the work, the assets and access it requires, and how progress can be assessed.</p><p>A single service can be the right starting point. The important part is understanding what happens before and after it, and using feedback from real inquiries to guide the next decision.</p><PrimaryButton href="/work" secondary>See the businesses in our portfolio</PrimaryButton></div></section>
 <Process/><section className="section container split-section"><div><p className="eyebrow">Beyond local services</p><h2>EXPERTISE HAS<br/>ANOTHER PATH.</h2></div><div className="prose"><p className="large-copy">For industry experts building education businesses, we offer a separate info product marketing service.</p><p>Coaches, consultants, educators, experts, and creators in real estate and home services can connect their knowledge to positioning, funnels, campaigns, and follow-up.</p><PrimaryButton href="/info-products" secondary>Explore Info Product Marketing</PrimaryButton></div></section><CTA title={'LOOKING FOR A\nMORE CONNECTED APPROACH?'} text="Tell us what your business does well and where the marketing is falling short. We can discuss whether our approach fits the work you need." label="Talk About Working Together"/></>;}
