import Link from 'next/link';
import Image from 'next/image';
import { Arrow, Reveal } from '@/components/interactive';
import { CTA, ServiceRows, WorkGrid } from '@/components/shared';
import { faq } from '@/lib/content';
import type { Metadata } from 'next';
export const metadata:Metadata={alternates:{canonical:'/'}};

export default function Home(){return <>
  <section className="hero container"><div className="hero-copy"><p className="eyebrow">Real estate & home service marketing</p><h1 className="display">Get seen.<br /><span className="highlight">Get chosen.</span></h1><p className="hero-description">Websites, search, and paid media that turn local attention into your next customer.</p><Link href="/contact" className="button">Start a project<Arrow /></Link></div><div className="hero-art"><Reveal className="hero-photo primary-photo"><Image src="/images/architecture.webp" alt="Contemporary home with clean architectural lines and warm wood details, conceptual imagery" width={1536} height={1024} sizes="(max-width:767px) 90vw, 43vw" priority /></Reveal><Reveal className="hero-photo secondary-photo" delay={0.12}><Image src="/images/interior.webp" alt="Bright renovated living space overlooking a garden, conceptual imagery" width={1536} height={1024} sizes="(max-width:767px) 45vw, 22vw" priority /></Reveal><span className="hero-mark" aria-hidden="true"><Arrow size={160}/></span></div></section>
  <nav className="channel-nav container" aria-label="Our capabilities"><Link href="/services/web-design">Web design<Arrow size={18}/></Link><Link href="/services/seo">SEO<Arrow size={18}/></Link><Link href="/services/meta-ads">Meta Ads<Arrow size={18}/></Link><Link href="/services/google-ads">Google Ads<Arrow size={18}/></Link></nav>
  <section className="intro-section container"><Reveal><p className="eyebrow">A clearer path to growth</p><h2>Great work deserves<br />to be the <span className="text-muted">obvious choice.</span></h2><p className="intro-body">You’ve built a business worth choosing. We connect the website, search presence, and campaigns that help the right people find it, trust it, and take the next step.</p></Reveal><div className="intro-principles"><div><span>Built around your market</span><p>Real estate and home services. Specific customers, specific decisions.</p></div><div><span>Connected from the start</span><p>Your message, your website, and your advertising working toward one goal.</p></div></div></section>
  <section className="section container"><div className="section-heading"><h2>The right pieces.<br />Working together.</h2><p>Start where it matters most. Build from there.</p></div><ServiceRows /></section>
  <section className="section industries-section container"><div className="section-heading"><h2>Your industry.<br />Our focus.</h2></div><div className="industry-grid"><Reveal><Link href="/industries/real-estate" className="industry-card"><div className="industry-photo"><Image src="/images/architecture.webp" alt="Contemporary home exterior, conceptual real estate imagery" width={1536} height={1024} sizes="(max-width:767px) 90vw, 50vw"/></div><div className="industry-content"><h3>Real estate</h3><Arrow size={30}/></div><p>Build a presence that earns the next listing conversation.</p><span className="text-link">Explore real estate marketing<Arrow size={18}/></span></Link></Reveal><Reveal delay={0.08}><Link href="/industries/home-services" className="industry-card"><div className="industry-photo"><Image src="/images/interior.webp" alt="Refined renovated living room, conceptual home services imagery" width={1536} height={1024} sizes="(max-width:767px) 90vw, 50vw"/></div><div className="industry-content"><h3>Home services</h3><Arrow size={30}/></div><p>Put your business in front of homeowners ready to act.</p><span className="text-link">Explore home service marketing<Arrow size={18}/></span></Link></Reveal></div></section>
  <section className="section work-section container"><div className="section-heading"><p className="eyebrow">Selected work</p><h2>Good businesses.<br />Stronger first impressions.</h2><p>A few of the websites we’ve helped bring to life.</p></div><WorkGrid /><Link href="/work" className="text-link all-work">Explore our work<Arrow /></Link></section>
  <section className="process-section container"><h2>From ambition<br />to action.</h2><div className="process-list">{[['Find the starting point','We look at your market, current marketing, and the customers you want to reach.'],['Build the path','We align the message, website, and channels around a clear next step.'],['Learn. Refine. Repeat.','We use performance and lead quality to decide what deserves more attention.']].map(([title,text])=><Reveal key={title}><h3>{title}</h3><p>{text}</p></Reveal>)}</div></section>
  <section className="info-banner container"><div><p className="eyebrow">For industry experts</p><h2>You know your craft.<br />Help more people learn it.</h2><p>Info product marketing for real estate and home service experts. Turn your knowledge into an offer people understand and a path they can follow.</p><Link href="/info-products" className="text-link">Explore info product marketing<Arrow /></Link></div><span className="info-type" aria-hidden="true">KNOW.<br />TEACH.<br />GROW.</span></section>
  <section className="faq-section container"><h2>A few good questions.</h2><div>{faq.map(([q,a])=><details className="faq" key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>
  <CTA />
</>;}
