import Link from 'next/link';
import {CustomerJourney,Arrow} from '@/components/interactive';
import {SectionHeader,PrimaryButton,ServiceRows,IndustryPanels,WorkGrid,ProjectCard,Principles,Process,FAQSection,CTA} from '@/components/shared';
import {projects,faq} from '@/lib/content';
import {insights} from '@/lib/insights';
import {pageMetadata} from '@/lib/site';

export const metadata=pageMetadata(
 'Real Estate & Home Service Marketing Agency',
 'Digital Pathway builds conversion-focused websites, SEO and AI search visibility, Google Ads, and Meta Ads for real estate and home service businesses.',
 '/'
);

export default function Home(){return <>
 <section className="home-hero dark"><div className="container"><div className="hero-topline"><p className="eyebrow">Real estate + home service marketing agency</p><span className="eyebrow hero-coordinate">Strategy → Experience → Acquisition</span></div><div className="hero-title-row"><h1><span>GET FOUND.</span><span>GET TRUSTED.</span><span>GET CHOSEN.</span></h1><div className="hero-path" aria-hidden="true"><span>01</span><i/><span>02</span><i/><span>03<Arrow size={30}/></span></div></div><div className="hero-bottom"><p>Digital Pathway connects conversion-focused websites, SEO and AI search visibility, Google Ads, and Meta Ads into one path from local attention to qualified inquiry.</p><div className="hero-actions"><PrimaryButton/><PrimaryButton href="/work" secondary>View Our Work</PrimaryButton></div></div><div className="hero-foot"><p>Web Design <span>/</span> SEO + AI Search <span>/</span> Google Ads <span>/</span> Meta Ads</p><a href="#selected-work">Scroll to explore <span aria-hidden="true">↓</span></a></div></div></section>
 <section id="selected-work" className="section container"><SectionHeader label="Selected work / 01" title={'WORK THAT MAKES\nTHE FIRST IMPRESSION COUNT.'}/><ProjectCard project={projects[0]} featured details/><div className="proof-index">{projects.slice(1).map((p,i)=><Link href={'/work/'+p.slug} key={p.slug} data-project={p.slug}><span className="eyebrow">0{i+2} / {p.category}</span><strong>{p.name}</strong><Arrow/></Link>)}</div></section>
 <section className="positioning-section section"><div className="container"><p className="eyebrow">The work deserves the attention</p><h2>GREAT WORK SHOULD<br/>BE EASIER<br/><span className="outline-type">TO CHOOSE.</span></h2><div className="positioning-copy"><span className="oversized-arrow" aria-hidden="true">↗</span><div><p className="large-copy">Your business may already deliver excellent work. Prospects are judging it before they ever speak with you.</p><p>We improve what they see when they search, click, compare, and decide. So the quality behind your business is easier to recognize.</p></div></div></div></section>
 <section className="section container"><SectionHeader label="The connected journey" title={'ONE PATH.\nEVERY TOUCHPOINT CONNECTED.'} text="Website, search, advertising, landing experience, and measurement. Aligned around the same customer decision."/><CustomerJourney/></section>
 <section className="section container"><SectionHeader label="What we do" title={'FOUR DISCIPLINES.\nONE GROWTH SYSTEM.'} text="Start with the constraint that matters most. Make every piece support the next."/><ServiceRows/></section>
 <section className="section answer-engine-section"><div className="container"><SectionHeader label="SEO + AI search" title={'BUILD FOR SEARCHERS.\nSTRUCTURE FOR ANSWERS.'} text="Answer engine optimization is not a replacement for SEO. It is the discipline of making strong search content easier to retrieve, understand, and use in answer-oriented experiences."/><div className="answer-engine-grid"><article><p className="eyebrow">What Digital Pathway does</p><h3>Make the business unambiguous.</h3><p>Clear service architecture, useful internal links, specific market language, direct answers, and accurate structured data help both people and search systems understand what the business does.</p></article><article><p className="eyebrow">What we do not promise</p><h3>No AI-citation shortcuts.</h3><p>No legitimate SEO or AEO work can guarantee a ChatGPT mention, Google AI citation, ranking, or recommendation. The goal is stronger discoverability, clarity, credibility, and conversion.</p></article></div><div className="answer-engine-actions"><PrimaryButton href="/services/seo">Explore SEO</PrimaryButton><PrimaryButton href="/insights/answer-engine-optimization-local-business" secondary>Read the AEO guide</PrimaryButton></div></div></section>
 <section className="section dark"><div className="container"><SectionHeader label="Who we help" title={'BUILT AROUND\nHOW YOUR MARKET BUYS.'}/><IndustryPanels/></div></section>
 <section className="section container"><SectionHeader label="The portfolio" title={'REAL BUSINESSES.\nWORK YOU CAN EXPLORE.'} text="Real estate, property staging, and development. See the websites behind the first impression."/><WorkGrid full selection={[projects[1],projects[2]]}/><div className="section-end"><PrimaryButton href="/work" secondary>Explore all our work</PrimaryButton></div></section>
 <section className="section contrast-section"><div className="container"><SectionHeader label="How we think" title={'NOT MORE MARKETING.\nBETTER CONNECTION\nBETWEEN IT.'}/><Principles/></div></section>
 <Process/>
 <section className="section container"><SectionHeader label="Insights" title={'ANSWER THE QUESTION.\nTHEN EARN THE TRUST.'} text="Practical guidance on local search, AI visibility, websites, and paid acquisition for the markets we serve."/><div className="insight-preview-grid">{insights.slice(0,3).map((article,index)=><Link className="insight-card" href={'/insights/'+article.slug} key={article.slug}><span className="eyebrow">0{index+1} / {article.category}</span><h3>{article.shortTitle}</h3><p>{article.description}</p><span className="insight-meta">{article.readingTime}</span><span className="text-link">Read the guide<Arrow/></span></Link>)}</div><div className="section-end"><PrimaryButton href="/insights" secondary>Explore all insights</PrimaryButton></div></section>
 <section className="section dark info-division"><div className="container info-division-grid"><div><p className="eyebrow">For industry experts / A separate offering</p><h2>TURN WHAT YOU KNOW<br/>INTO SOMETHING PEOPLE<br/>WANT TO LEARN.</h2><p>Info product marketing for real estate and home-service coaches, consultants, educators, experts, and creators. Connect your knowledge to a clear offer and a path to enrollment.</p><PrimaryButton href="/info-products" secondary>Explore Info Product Marketing</PrimaryButton></div><div className="info-division-type" aria-hidden="true"><span>KNOW.</span><span>TEACH.</span><span>GROW.</span></div></div></section>
 <FAQSection items={faq}/><CTA/>
 </>;
}
