'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {businessTypes,serviceChoices,validateInquiry,type Inquiry} from '@/lib/inquiry';
import {track} from '@/lib/tracking';
import {Arrow} from './interactive';
const initial:Inquiry={name:'',email:'',company:'',website:'',businessType:'',services:[],goal:'',timeline:'',consent:false,website_confirm:''};
const titles=['About you','Your business','The right starting point','Your primary goal'];
export function ProjectForm({email,available}:{email:string;available:boolean}){
 const [data,setData]=useState<Inquiry>(initial);const [step,setStep]=useState(0);const [errors,setErrors]=useState<Record<string,string>>({});const [status,setStatus]=useState<'idle'|'sending'|'success'>('idle');const started=useRef(false);const heading=useRef<HTMLHeadingElement>(null);const firstRender=useRef(true);const formRef=useRef<HTMLFormElement>(null);const submitLock=useRef(false);const requestId=useRef('');
 useEffect(()=>{if(new URLSearchParams(location.search).get('service')==='info-products')setData(d=>({...d,businessType:'Info Product',services:['Info Product Marketing']}));},[]);
 useEffect(()=>{if(firstRender.current){firstRender.current=false;return;}heading.current?.focus();},[step,status]);
 function change<K extends keyof Inquiry>(key:K,value:Inquiry[K]){setData(d=>({...d,[key]:value}));setErrors(e=>({...e,[key]:'',form:''}));requestId.current='';}
 function begin(){if(!started.current){started.current=true;track('form_start');}}
 function advance(e:FormEvent){e.preventDefault();const v=validateInquiry(data);const keys=[['name','email','company','website'],['businessType'],['services'],['goal','consent']][step];const nextErrors=v.ok?{}:Object.fromEntries(Object.entries(v.errors).filter(([k])=>keys.includes(k)));setErrors(nextErrors);if(Object.keys(nextErrors).length){requestAnimationFrame(()=>formRef.current?.querySelector<HTMLElement>('[aria-invalid="true"]')?.focus());return;}track('form_step_complete',{step:step+1});if(step<3)setStep(s=>s+1);else void send();}
 async function send(){if(submitLock.current)return;submitLock.current=true;setStatus('sending');setErrors({});if(!requestId.current)requestId.current=crypto.randomUUID();
 try{const res=await fetch('/api/inquiries',{method:'POST',headers:{'Content-Type':'application/json','X-Idempotency-Key':requestId.current},body:JSON.stringify(data),signal:AbortSignal.timeout(20000)});const body=await res.json();if(!res.ok||body.ok!==true){setErrors({...body.errors,form:body.error||'We could not confirm receipt. Please try again.'});setStatus('idle');return;}setStatus('success');track('form_submit',{business_type:data.businessType,service_count:data.services.length});setData(initial);
 }catch{setStatus('idle');setErrors({form:'We could not confirm receipt. Please try again or email '+email+'.'});}finally{submitLock.current=false;}}
 const attrs=(name:string)=>({'aria-invalid':Boolean(errors[name]),'aria-describedby':errors[name]?name+'-error':undefined});
 const error=(name:string)=>errors[name]?<span className="field-error" id={name+'-error'}>{errors[name]}</span>:null;
 if(status==='success')return <div className="form-success" role="status"><p className="eyebrow">Project received</p><h2 ref={heading} tabIndex={-1}>THANKS.<br/>WE HAVE YOUR<br/>PROJECT DETAILS.</h2><p>Someone from Digital Pathway will review your information and follow up using the email you provided.</p><a className="text-link" href="/work">Explore our work<Arrow/></a></div>;
 return <form ref={formRef} className="project-form" onSubmit={advance} noValidate onFocus={begin} aria-busy={status==='sending'}>
 <div className="form-progress" aria-label={'Step '+(step+1)+' of 4'}>{titles.map((t,i)=><span className={i<=step?'complete':''} key={t}><i/>{i+1}</span>)}</div><p className="eyebrow">Step 0{step+1} / 04</p><h2 ref={heading} tabIndex={-1}>{titles[step]}</h2>
 {!available?<p className="form-availability" role="status">Online inquiries are temporarily unavailable. You can contact us directly at <a href={'mailto:'+email}>{email}</a>.</p>:null}
 <div className="honeypot" aria-hidden="true"><label>Leave this field blank<input tabIndex={-1} autoComplete="off" name="website_confirm" value={data.website_confirm} onChange={e=>change('website_confirm',e.target.value)}/></label></div>
 {step===0?<div className="form-fields"><label htmlFor="name">Your name<input id="name" name="name" autoComplete="name" required maxLength={100} value={data.name} onChange={e=>change('name',e.target.value)} {...attrs('name')}/>{error('name')}</label><label htmlFor="email">Email address<input id="email" name="email" type="email" autoComplete="email" required maxLength={180} value={data.email} onChange={e=>change('email',e.target.value)} {...attrs('email')}/>{error('email')}</label><label htmlFor="company">Company<input id="company" aria-label="Company" name="company" autoComplete="organization" required maxLength={120} value={data.company} onChange={e=>change('company',e.target.value)} {...attrs('company')}/>{error('company')}</label><label htmlFor="website">Website <span className="optional">(optional)</span><input id="website" name="website" type="text" inputMode="url" autoComplete="url" maxLength={250} placeholder="yourwebsite.com" value={data.website} onChange={e=>change('website',e.target.value)} {...attrs('website')}/>{error('website')}</label></div>:null}
 {step===1?<fieldset className="choice-fieldset"><legend>Which best describes your business?</legend>{businessTypes.map(n=><label className="form-choice" key={n}><input type="radio" name="businessType" value={n} checked={data.businessType===n} onChange={()=>change('businessType',n)} {...attrs('businessType')}/><span>{n}</span><Arrow size={18}/></label>)}{error('businessType')}</fieldset>:null}
 {step===2?<fieldset className="choice-fieldset"><legend>What do you need? Select all that apply.</legend>{serviceChoices.map(n=><label className="form-choice" key={n}><input type="checkbox" name="services" value={n} checked={data.services.includes(n)} onChange={e=>change('services',e.target.checked?[...data.services,n]:data.services.filter(s=>s!==n))} {...attrs('services')}/><span>{n}</span></label>)}{error('services')}</fieldset>:null}
 {step===3?<div className="form-fields"><label htmlFor="goal">What are you trying to achieve?<textarea id="goal" name="goal" rows={5} required minLength={10} maxLength={3000} placeholder="Tell us where things stand and what you want to improve." value={data.goal} onChange={e=>change('goal',e.target.value)} {...attrs('goal')}/>{error('goal')}</label><label htmlFor="timeline">Anything we should know about timing? <span className="optional">(optional)</span><input id="timeline" name="timeline" maxLength={120} value={data.timeline} onChange={e=>change('timeline',e.target.value)}/></label><label className="consent"><input type="checkbox" name="consent" checked={data.consent} onChange={e=>change('consent',e.target.checked)} {...attrs('consent')}/><span>Digital Pathway may use these details to review my project and respond to my inquiry.</span></label>{error('consent')}<p className="form-note">Your details are used to respond to this request. This does not subscribe you to a marketing list.</p></div>:null}
 {errors.form?<div role="alert" className="form-error">{errors.form}</div>:null}
 <div className="form-actions">{step>0?<button type="button" className="text-link" onClick={()=>{setStep(s=>s-1);setErrors({});}} disabled={status==='sending'}>← Back</button>:<span className="form-note">A clear starting point.</span>}<button className="button" type="submit" disabled={status==='sending'||(step===3&&!available)}>{status==='sending'?'Sending…':step===3?'Send Project Details':'Continue'}<Arrow/></button></div>
 </form>;
}
