import Link from 'next/link';
import Image from 'next/image';
import {Arrow} from './interactive';
import {services,industries,projects,process,principles,type Project,type FAQ} from '@/lib/content';
import {siteUrl,contactEmail} from '@/lib/site';

export function JsonLd({data}:{data:unknown}){return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data).replace(/</g,'\\u003c')}}/>;}
export function Breadcrumb({items}:{items:{name:string;href:string}[]}){return <><nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link>{items.map((i,n)=><span key={i.href}><span aria-hidden="true">/</span>{n===items.length-1?<span aria-current="page">{i.name}</span>:<Link href={i.href}>{i.name}</Link>}</span>)}</nav><JsonLd data={{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{name:'Home',href:'/'},...items].map((i,n)=>({'@type':'ListItem',position:n+1,name:i.name,item:siteUrl+i.href}))}}/></>;}
export function PrimaryButton({children='Start a Project',href='/contact',secondary=false}:{children?:React.ReactNode;href?:string;secondary?:boolean}){return <Link href={href} className={secondary?'text-link':'button'}>{children}<Arrow/></Link>;}
export function SectionHeader({label,title,text}:{label:string;title:string;text?:string}){return <div className="section-heading"><p className="eyebrow">{label}</p><div><h2 className="pre-line">{title}</h2>{text?<p className="section-intro">{text}</p>:null}</div></div>;}
export function PageHero({label,title,text,children,breadcrumb}:{label:string;title:string;text:string;children?:React.ReactNode;breadcrumb?:{name:string;href:string}[]}){return <section className="page-hero dark"><div className="container">{breadcrumb?<Breadcrumb items={breadcrumb}/>:null}<p className="eyebrow">{label}</p><h1 className="pre-line">{title}</h1><div className="hero-bottom"><p>{text}</p><div className="hero-actions">{children||<PrimaryButton/>}</div></div></div></section>;}
export function CTASection({title='READY TO BECOME\nTHE OBVIOUS CHOICE?',text='Tell us where you are, what you are trying to grow, and what is getting in the way.',href='/contact',label='Start a Project'}:{title?:string;text?:string;href?:string;label?:string}){return <section className="cta-section dark"><div className="container"><p className="eyebrow">Your next move</p><div className="cta-grid"><div><h2 className="pre-line">{title}</h2><p>{text}</p><PrimaryButton href={href}>{label}</PrimaryButton></div><span className="cta-arrow" aria-hidden="true"><Arrow size={180}/></span></div></div></section>;}
export const CTA=CTASection;
export function ServiceRow({service:s,index}:{service:typeof services[number];index:number}){return <Link className="service-row" href={'/services/'+s.slug}><span className="service-index eyebrow">0{index+1}</span><div className="service-name"><h3>{s.name}</h3><span className="service-stage">{s.stage}</span></div><div className="service-copy"><p>{s.description}</p><span className="service-explore">Explore {s.name}</span></div><span className={'service-glyph glyph-'+s.slug} aria-hidden="true">{s.slug==='web-design'?<><i/><i/><i/></>:s.slug==='seo'?<><i/><i/><i/><i/></>:s.slug==='google-ads'?<><i/><i/><i/></>:<><i/><i/></>}</span><Arrow size={28}/></Link>;}
export function ServiceRows(){return <div className="service-rows">{services.map((s,i)=><ServiceRow key={s.slug} service={s} index={i}/>)}</div>;}
export function ProjectCard({project:p,index=0,featured=false,details=false}:{project:Project;index?:number;featured?:boolean;details?:boolean}){
 return <article className={'project-card '+(featured?'project-featured':'')}><a className="project-visual-link" href={p.url} target="_blank" rel="noopener noreferrer" data-project={p.slug} aria-label={'Visit '+p.name+' website (opens in a new tab)'}>
 <div className="project-stage"><div className="browser-frame"><div className="browser-bar"><span aria-hidden="true">● ● ●</span><span>{new URL(p.url).hostname.replace(/^www\./,'')}</span><Arrow size={12}/></div><div className="project-screen"><Image src={p.image} alt={p.alt} width={1350} height={920} sizes={featured?'(max-width: 767px) 90vw, 85vw':'(max-width: 767px) 90vw, 44vw'}/></div></div><span className="project-visit">Visit website<Arrow/></span></div></a>
 <div className="project-caption"><span className="eyebrow">0{index+1} / {p.category}</span><h3>{p.name}</h3><p>{p.description}</p>{details?<Link className="text-link" data-project={p.slug} href={'/work/'+p.slug}>View project<Arrow/></Link>:null}</div></article>;
}
export const CaseStudyCard=ProjectCard;
export function WorkGrid({full=false,selection=projects}:{full?:boolean;selection?:Project[]}){return <div className="work-grid">{selection.map((p,i)=><CaseStudyCard key={p.slug} project={p} index={i} featured={i===0} details={full}/>)}</div>;}
export function IndustryPanel({industry:i}:{industry:typeof industries[number]}){return <Link href={'/industries/'+i.slug} className="industry-panel"><div className="industry-image"><Image src={i.image} alt={i.alt} width={1536} height={1024} sizes="(max-width: 767px) 90vw, 44vw"/></div><div className="industry-heading"><h3>{i.name}</h3><Arrow size={32}/></div><p>{i.slug==='real-estate'?'Turn local expertise, reputation, and inventory into a digital presence people remember when it is time to choose.':'Capture demand when homeowners search, compare, and decide who they trust with their property.'}</p><span className="industry-audience">{i.audience.join(' / ')}</span><span className="text-link">{i.name} Marketing<Arrow/></span></Link>;}
export function IndustryPanels(){return <div className="industry-grid">{industries.map(i=><IndustryPanel industry={i} key={i.slug}/>)}</div>;}
export function ProcessStep({title,text,index}:{title:string;text:string;index:number}){return <li className="process-step"><span className="eyebrow">0{index+1}</span><div><h3>{title}</h3><p>{text}</p></div><span className="process-line" aria-hidden="true"/></li>;}
export function Process(){return <section className="section container process-section"><div className="sticky-heading"><p className="eyebrow">How we work</p><h2>FROM WHERE YOU ARE<br/>TO WHERE YOU<br/>WANT TO GO.</h2></div><ol className="process-list">{process.map(([h,p],i)=><ProcessStep key={h} title={h} text={p} index={i}/>)}</ol></section>;}
export function Principles(){return <div className="principles-grid">{principles.map(([h,p],i)=><div key={h}><span className="eyebrow">0{i+1}</span><h3>{h}</h3><p>{p}</p></div>)}</div>;}
export function FAQAccordion({items}:{items:readonly FAQ[]}){return <div className="faq-list">{items.map(([q,a])=><details className="faq" key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div>;}
export function FAQSection({items}:{items:readonly FAQ[]}){return <><section className="section container faq-section"><div><p className="eyebrow">Before we begin</p><h2>GOOD<br/>QUESTIONS.</h2><p>Clear answers make for a better starting point.</p></div><FAQAccordion items={items}/></section><JsonLd data={{'@context':'https://schema.org','@type':'FAQPage',mainEntity:items.map(([question,answer])=>({'@type':'Question',name:question,acceptedAnswer:{'@type':'Answer',text:answer}}))}}/></>;}
export function Footer(){return <footer className="footer dark"><div className="container"><div className="footer-grid"><div className="footer-intro"><Link href="/" className="wordmark">digital pathway<span aria-hidden="true">↗</span></Link><p>Connected marketing for the businesses<br/>that shape where we live.</p><a className="text-link footer-email" href={'mailto:'+contactEmail}>{contactEmail}<Arrow size={18}/></a></div><div><h2 className="eyebrow">Services</h2><Link href="/services">All services</Link>{services.map(s=><Link key={s.slug} href={'/services/'+s.slug}>{s.name}</Link>)}</div><div><h2 className="eyebrow">Explore</h2><Link href="/industries">Who We Help</Link><Link href="/industries/real-estate">Real Estate</Link><Link href="/industries/home-services">Home Services</Link><Link href="/work">Our Work</Link><Link href="/insights">Insights</Link><Link href="/info-products">Info Products</Link><Link href="/about">About</Link><Link href="/contact">Start a Project</Link></div></div><div className="footer-signature" aria-hidden="true">DIGITAL PATHWAY<span>↗</span></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Digital Pathway</span><span>Clarity. Connection. Direction.</span><Link href="#main">Back to top ↑</Link></div></div></footer>;}
