export type FAQ = readonly [string, string];
export type Project = {
  slug: string; name: string; category: string; description: string; url: string;
  image: string; alt: string; services?: string[]; problem?: string; strategy?: string;
  execution?: string; results?: string; gallery?: {src:string;alt:string}[];
  testimonial?: {quote:string;attribution:string};
};
export const projects: Project[] = [
 {slug:'dana-williams',name:'Dana Williams',category:'Real estate',description:'A personal online presence for a real estate professional.',url:'https://myrealtordanawilliams.com/',image:'/images/dana.webp',alt:'Dana Williams real estate website homepage'},
 {slug:'henry-clay-co',name:'Henry Clay Co.',category:'Home & interiors',description:'An editorial presentation for a property staging business.',url:'https://www.henryclayco.com/',image:'/images/henry.webp',alt:'Henry Clay Co. property staging website homepage'},
 {slug:'onu-ventures',name:'Onu Ventures',category:'Real estate development',description:'A digital home for a real estate development business.',url:'https://www.onuventuresinc.com/',image:'/images/onu.webp',alt:'Onu Ventures real estate development website homepage'}
];
export const services = [
 {slug:'web-design',name:'Web Design',short:'Web Design',line:'YOUR WEBSITE SHOULD\nDO MORE THAN\nLOOK GOOD.',intro:'It should clarify what you do, establish trust, and move qualified prospects toward the next action.',description:'Turn your website into a clear path from first impression to serious inquiry.',stage:'The place where attention becomes action.',problemTitle:'A good impression is only the beginning.',problem:'A visitor should not have to piece together your services, search for evidence, or work out how to contact you. Every unanswered question creates another reason to leave.',outcome:'A website that represents the quality of your work and gives the right prospects a clear next step.',items:[['Conversion strategy','Connect the offer, page structure, proof, and primary action before designing the interface.'],['Custom design & development','A distinctive, responsive experience built around your business and the way your customers decide.'],['Service, location & landing pages','Give different searches and campaigns a relevant destination, with clear content and internal links.'],['Forms, booking paths & tracking','Reduce the steps between interest and inquiry. Define meaningful events and the integrations needed to measure them.']],connection:'Search brings people with a question. Advertising creates a reason to visit. Your website has to carry that intent through to a useful conversation.',considerations:['Information architecture and copy structure','Mobile usability and image performance','Technical SEO foundations','Analytics and integration requirements'],faqs:[['Do I need a completely new website?','Not always. We review the existing structure, performance, and conversion path first. A focused improvement may make more sense than a rebuild.'],['Do you build websites from scratch?','Yes. Custom responsive design and development are part of our web design offering. The platform, pages, and integrations are agreed around the project.'],['Can you create landing pages for campaigns?','Yes. Service, location, and landing pages can be scoped around your campaigns and the next action you want visitors to take.'],['Are booking tools and integrations included?','We discuss the forms, booking paths, and tracking the project needs. Specific integrations, access requirements, and costs are confirmed in the scope.']]},
 {slug:'seo',name:'SEO',short:'SEO',line:'BE THERE WHEN\nTHE SEARCH STARTS.',intro:'Build visibility around the services people are already searching for in the markets you serve.',description:'Build visibility around the services people are already searching for in the markets you serve.',stage:'The answer to a relevant search.',problemTitle:'Great work is hard to choose when it is hard to find.',problem:'A technically sound website is a starting point. It also needs useful pages that match real searches, clear service information, and signals that help people understand where and how you work.',outcome:'A stronger foundation for relevant organic traffic, built around your actual services and market.',items:[['Technical & on-page SEO','Identify issues that affect crawling, indexing, page structure, and how clearly your content communicates.'],['Local search strategy','Align your Google Business Profile strategy and website with the services and areas you genuinely cover.'],['Service & location content','Organize useful content around search intent, connect related pages, and answer the questions behind the search.'],['Search measurement','Establish a baseline for relevant visibility, traffic, and inquiries so progress has context.']],connection:'SEO creates an enduring route into your website. Paid search can complement that work by testing demand and messaging while organic visibility develops.',considerations:['Search intent and page priorities','Internal linking and content gaps','Google Business Profile opportunities','Technical health and measurement'],faqs:[['How quickly can SEO produce results?','Timing depends on your starting point, competition, and the work required. We establish a baseline and a realistic plan before work begins. Rankings and results are not guaranteed.'],['Do you work on local SEO?','Yes. Local search and Google Business Profile strategy sit alongside technical, on-page, service, and location content work.'],['How does SEO fit with paid advertising?','Both should reflect the same services, market, and message. Paid search can provide faster feedback on demand while SEO builds a stronger organic foundation.'],['Do we need a page for every location?','Only where a page serves a real customer need and reflects an area you actually serve. Repeating the same content across place names is not a useful strategy.']]},
 {slug:'google-ads',name:'Google Ads',short:'Google Ads',line:'CAPTURE DEMAND\nWHEN INTENT\nIS HIGHEST.',intro:'Meet high-intent demand with campaigns and landing pages built around what people are actually searching for.',description:'Meet high-intent demand with campaigns and landing pages built around what people are actually searching for.',stage:'Be relevant in the moment of intent.',problemTitle:'The click is only half the experience.',problem:'Someone searches for a specific service. The ad earns their attention. If the page they land on changes the subject, that intent is lost. The campaign and landing page need to answer the same question.',outcome:'A clearer view of which searches and campaigns lead to useful conversations for your business.',items:[['Search intent & keyword research','Understand the services, queries, and customer decisions the campaign should address.'],['Campaign structure & ad copy','Organize relevant searches and messages around a focused offer and a clear next step.'],['Landing page alignment','Carry the promise of the ad into the headline, evidence, and inquiry path on the page.'],['Call, form & conversion tracking','Define meaningful actions and connect measurement to the inquiries you want to generate.']],connection:'Google Ads captures existing demand. The website earns trust after the click, and SEO strengthens the wider search presence. Lead-quality feedback informs the next improvement.',considerations:['Negative keyword opportunities','Budget allocation and campaign structure','Conversion measurement and attribution limits','Lead quality and landing page friction'],faqs:[['Is ad spend included in the agency fee?','Media spend and agency scope are discussed separately in your proposal. Budget should reflect your market, customer value, capacity, and growth goal.'],['Do we need a dedicated landing page?','Often a relevant existing service page can work. When the offer, audience, or conversion goal is different, a dedicated page can provide a clearer experience.'],['How will we know whether the leads are useful?','Call and form measurement should be paired with your feedback on inquiries. Volume alone does not explain whether a campaign is reaching the right customers.'],['Do you guarantee a cost per lead?','No fixed result is promised on this site. Competition, budget, offer, seasonality, and the conversion experience all affect performance.']]},
 {slug:'meta-ads',name:'Meta Ads',short:'Meta Ads',line:'TURN ATTENTION\nINTO DEMAND.',intro:'Give the right people a compelling reason to stop scrolling and start a conversation.',description:'Turn attention into demand with stronger creative, positioning, offers, and conversion paths.',stage:'Build interest before the search.',problemTitle:'The message has to earn the attention.',problem:'People are not opening Facebook or Instagram to read your sales pitch. The creative needs to make the service relevant, show why it matters, and give them a natural next step.',outcome:'A deliberate path from ad creative to inquiry, with testing informed by lead quality.',items:[['Offer & audience strategy','Connect what you sell with the people it helps, the decision they face, and a reason to act.'],['Creative concepts & campaigns','Build messaging and campaign concepts around your work, your offer, and the objections that matter.'],['Landing pages & retargeting','Continue the message after the click and support the decision beyond a single interaction.'],['Testing & conversion measurement','Use behavior and inquiry quality to learn which combinations deserve more attention.']],connection:'Meta Ads creates awareness and consideration. Your website supplies the detail and proof. Search can help people find you again when they are ready to act.',considerations:['Creative and message-market fit','Offer clarity and audience relevance','Campaign structure and testing priorities','Tracking access and follow-up readiness'],faqs:[['Can Meta Ads work for a local business?','The right approach depends on the service, market, and offer. Visual services and considered purchases can benefit from showing the work and building familiarity.'],['Is this only media buying?','No. Our existing offering includes offer and audience strategy, creative concepts, campaigns, landing pages, retargeting, testing, and conversion measurement.'],['Do you handle both Google Ads and Meta Ads?','Yes. The channels serve different moments in the decision. We discuss the right starting point based on your offer and where the constraint is.'],['What creative assets will you need?','We review the project imagery, existing creative, offer, and business information available. Production needs and responsibilities are confirmed in the scope.']]}
];
export const industries = [
 {slug:'real-estate',name:'Real Estate',title:'WIN THE CONVERSATION\nBEFORE THE SHOWING.',description:'For agents, teams, brokerages, developers, and property businesses ready to turn local expertise into a stronger digital presence.',image:'/images/architecture.webp',alt:'Conceptual contemporary residential architecture, used as industry illustration',audience:['Agents','Teams','Brokerages','Developers','Property businesses'],body:'Your next client is comparing more than properties. They are comparing the people behind them. Long before a showing or listing conversation, your website, search presence, and advertising are shaping their decision.',priorities:[['Position your expertise','Make your perspective, market knowledge, and services easy to understand before the first conversation.'],['Build local relevance','Connect service and community content with the questions buyers and sellers actually ask.'],['Create a clear inquiry path','Give listing, seller, and property campaigns a relevant destination and a direct next step.'],['Learn from real conversations','Connect lead capture and measurement to the types of inquiries your business wants.']]},
 {slug:'home-services',name:'Home Services',title:'MORE OF THE JOBS\nYOU ACTUALLY WANT.',description:'Marketing for contractors and home service businesses that want their digital presence to reflect the quality of their work.',image:'/images/interior.webp',alt:'Conceptual renovated interior, used as home services industry illustration',audience:['Contractors','Remodelers','HVAC','Plumbing','Electrical','Roofing','Landscaping','Specialty trades'],body:'A homeowner searches, compares, evaluates, and calls. At every step, they are looking for signs that you understand the job and can be trusted with their property. Your marketing should make that judgment easier.',priorities:[['Make your services clear','Explain the work you do, the areas you genuinely serve, and the jobs you want more of.'],['Show the quality','Use actual project imagery and verified evidence to help homeowners understand what they can expect.'],['Remove mobile friction','Make pages fast to navigate and calls or quote requests easy to find when someone is ready.'],['Connect intent to inquiry','Align local search, advertising, landing pages, and conversion tracking around a useful next action.']]}
];
export const principles = [
 ['Strategy before channels','Start with the offer, customer, market, and constraint. Then choose the work that will make the biggest difference.'],
 ['Message before media','The website and the advertisements should tell the same story. A click should feel like a continuation.'],
 ['Conversion before traffic','Give visitors a reason to trust you and an easy next step before asking more people to visit.'],
 ['Measurement before assumptions','Track calls, forms, appointments, and lead quality wherever the tools and access make it possible.']
];
export const process = [
 ['Diagnose','Understand the market, current marketing, customer journey, and primary constraint.'],
 ['Design','Build the message, experience, campaign, or acquisition system around the decision you want to earn.'],
 ['Launch','Bring the work live with the agreed tracking and conversion measurement in place.'],
 ['Optimize','Use actual behavior and lead quality to decide what deserves improvement.']
];
export const faq: FAQ[] = [
 ['Who does Digital Pathway work with?','Our core focus is real estate and home service businesses. We also offer a separate info product marketing service for coaches, consultants, educators, experts, and creators in these industries.'],
 ['Can we hire you for only one service?','Yes. The starting point should follow your most important constraint. That might be a website, local search visibility, or one advertising channel.'],
 ['Do you build websites from scratch?','Yes. We offer custom responsive design and development. We can also assess whether improving your existing website is the better starting point.'],
 ['Do you handle both Google Ads and Meta Ads?','Yes. Google Ads can capture existing search demand. Meta Ads can build interest and consideration. The right mix depends on your business and offer.'],
 ['How does SEO fit with paid advertising?','They should reinforce the same services, market, and message. Paid advertising can test demand while SEO builds a stronger organic foundation.'],
 ['Do you work with businesses outside real estate and home services?','These are our core markets, including property-related businesses. Tell us about your business so we can discuss whether the fit makes sense.'],
 ['What does a project typically start with?','Your goals, current marketing, audience, and main constraint. We use that context to discuss priorities and define a scope.'],
 ['Is advertising spend included in agency fees?','Media spend and agency scope are discussed separately in your proposal. There are no fixed budgets or minimums published on this site.'],
 ['How do you measure performance?','We define the goal before launch. Depending on the project and available integrations, that can include relevant traffic, calls, quote requests, appointments, lead quality, and conversions.'],
 ['Do you guarantee results?','No guaranteed rankings, revenue, lead volumes, or advertising returns are promised. We agree the scope and measurement approach, then use evidence to guide improvements.']
];
