export const services = [
  { slug: 'web-design', name: 'Web design', line: 'Make the first impression count.', intro: 'Turn your website into a clear path from first visit to serious inquiry.', description: 'Fast, distinctive websites that make your value clear and make the next step easy.', items: ['Conversion-focused page strategy', 'Custom responsive design and development', 'Service, location, and landing pages', 'Forms, booking paths, and event tracking'], outcome: 'A website that represents the quality of your work and helps visitors take the next step.', question: 'Do I need a completely new website?', answer: 'Not always. We look at your current structure, performance, and conversion path first. A focused improvement may make more sense than a full rebuild.' },
  { slug: 'seo', name: 'Search engine optimization', short: 'SEO', line: 'Be found where it matters.', intro: 'Show up when people search for the services you offer, in the places you serve.', description: 'Technical foundations, local visibility, and useful content built around how your customers search.', items: ['Technical and on-page SEO', 'Local search and Google Business Profile strategy', 'Service and location content', 'Search visibility and inquiry reporting'], outcome: 'A stronger foundation for relevant organic traffic, built around your actual services and market.', question: 'How quickly can SEO produce results?', answer: 'Timing depends on your starting point, competition, and the work required. We establish a baseline and a realistic plan before work begins. Rankings and results are not guaranteed.' },
  { slug: 'meta-ads', name: 'Meta Ads', line: 'Turn attention into intent.', intro: 'Give the right people a compelling reason to stop scrolling and start a conversation.', description: 'Facebook and Instagram campaigns with creative, messaging, and landing pages working together.', items: ['Offer and audience strategy', 'Creative concepts and campaign development', 'Landing pages and retargeting', 'Testing and conversion measurement'], outcome: 'A deliberate path from ad creative to inquiry, with ongoing testing informed by lead quality.', question: 'Can Meta Ads work for a local business?', answer: 'The right approach depends on the service, market, and offer. Visual services and considered purchases can benefit from showing the work and building familiarity before someone is ready to inquire.' },
  { slug: 'google-ads', name: 'Google Ads', line: 'Meet demand in the moment.', intro: 'Reach people actively searching for your service and give them a relevant place to land.', description: 'Search campaigns focused on commercial intent, relevant landing pages, and measurable inquiries.', items: ['Search intent and keyword research', 'Campaign structure and ad copy', 'Landing page message match', 'Call, form, and conversion tracking'], outcome: 'A clearer view of which searches and campaigns lead to useful conversations for your business.', question: 'Is ad spend included in the management fee?', answer: 'Media spend and agency scope are discussed separately in your proposal. Your budget should reflect your market, customer value, capacity, and growth goal.' },
];

export const industries = [
  { slug: 'real-estate', name: 'Real estate', title: 'Win the conversation. Before the showing.', description: 'For agents, teams, brokerages, and property businesses ready to turn local expertise into a stronger digital presence.', image: '/images/architecture.webp', alt: 'Conceptual contemporary home with pale concrete and warm wood details', audience: ['Agents and real estate teams', 'Independent and multi-office brokerages', 'Developers and property businesses'], priorities: ['Make your local expertise visible', 'Build confidence before the first call', 'Connect campaigns to qualified inquiries'], body: 'Your next client is comparing more than properties. They are comparing the people behind them. We bring your positioning, website, search presence, and advertising together so the right people understand why they should choose you.' },
  { slug: 'home-services', name: 'Home services', title: 'More of the jobs you want.', description: 'For contractors and home service businesses that want their marketing to reflect the quality of their work.', image: '/images/interior.webp', alt: 'Conceptual renovated living room with oak cabinetry and large garden windows', audience: ['Builders, remodelers, and contractors', 'HVAC, plumbing, and electrical businesses', 'Roofing, landscaping, and specialist trades'], priorities: ['Reach homeowners in your service area', 'Show the quality behind your business', 'Make quotes and calls easy to request'], body: 'When a homeowner needs help, trust and timing matter. We build a clear path from the first search or ad to the first inquiry, with messaging around your services, service area, and the reasons to call you.' },
];

export const projects = [
  { name: 'Dana Williams', category: 'Real estate', description: 'A personal online presence for a real estate professional.', url: 'https://myrealtordanawilliams.com/', image: '/images/dana.webp', alt: 'Dana Williams real estate website homepage' },
  { name: 'Henry Clay Co.', category: 'Home & interiors', description: 'An editorial presentation for a property staging business.', url: 'https://www.henryclayco.com/', image: '/images/henry.webp', alt: 'Henry Clay Co. property staging website homepage' },
  { name: 'Onu Ventures', category: 'Real estate development', description: 'A digital home for a real estate development business.', url: 'https://www.onuventuresinc.com/', image: '/images/onu.webp', alt: 'Onu Ventures real estate development website homepage' },
];

export const faq = [
  ['Who do you work with?', 'Our core focus is real estate and home service businesses. We also offer a separate info product marketing service for coaches, consultants, educators, and experts in these industries.'],
  ['Can we start with one service?', 'Yes. The starting point should follow your most important constraint. That might be a website, local search visibility, or one advertising channel.'],
  ['How much does it cost?', 'We scope each project around your goals, existing assets, market, and the work involved. Start a project inquiry and we can discuss scope and budget. Advertising spend is considered separately.'],
  ['How do you measure progress?', 'We define the goal before launch. Depending on the project, that can include relevant search traffic, calls, quote requests, appointments, lead quality, and conversions.'],
  ['Do you offer info product marketing?', 'Yes. We help real estate and home service experts market courses, coaching, memberships, and education offers through positioning, funnels, campaigns, and follow-up.'],
];
