import Link from 'next/link';
import {notFound} from 'next/navigation';
import {services,projects,type FAQ} from '@/lib/content';
import {pageMetadata,siteUrl} from '@/lib/site';
import {PageHero,SectionHeader,PrimaryButton,WorkGrid,Process,FAQSection,CTA,JsonLd} from '@/components/shared';
import {Arrow} from '@/components/interactive';

export function generateStaticParams(){return services.map(s=>({slug:s.slug}));}

export async function generateMetadata({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const s=services.find(s=>s.slug===slug);if(!s)notFound();
 if(slug==='seo')return pageMetadata('SEO & AI Search for Real Estate & Home Services','Build visibility across Google Search, local results, and AI-powered answer experiences with technical SEO, useful content, local strategy, and accurate structured data.','/services/'+slug);
 return pageMetadata(s.name+' for Real Estate & Home Services',s.intro,'/services/'+slug);
}

export default async function Service({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const s=services.find(s=>s.slug===slug);if(!s)notFound();const isSeo=slug==='seo';
 const aeoFaqs:FAQ[]=isSeo?[
  ['Do you optimize for AI search and answer engines?','Yes. We treat AI search visibility as part of strong SEO: crawlable pages, clear answers, useful internal links, consistent business information, credible evidence, and structured data that matches visible content.'],
  ['Do we need special AI schema?','No special AI schema is required. We use established structured data types when they accurately describe the page and help search systems understand the business, services, articles, breadcrumbs, or FAQs.'],
  ['Does llms.txt improve Google rankings?','Google has stated that llms.txt is not used for Google Search rankings or its generative search features. It can be maintained as optional compatibility documentation, but it is not a substitute for crawlable, useful pages.'],
  ['Can you guarantee citations in ChatGPT or Google AI?','No. No legitimate SEO or AEO work can guarantee a specific ranking, citation, recommendation, or answer-engine mention. The goal is to improve discoverability, clarity, relevance, and credibility for the questions your customers ask.']
 ]:[];
 const faqItems:FAQ[]=[...s.faqs.map(([q,a])=>[q,a] as const),...aeoFaqs];
 const serviceDescription=isSeo?'Search engine optimization and AI search visibility for real estate and home service businesses, including technical SEO, local strategy, useful content, internal linking, and accurate structured data.':s.intro;
 return <>
 <PageHero label={isSeo?'SEO + AI Search':s.name} title={s.line} text={isSeo?'Build visibility around the services people are searching for across traditional search, local results, and answer-oriented experiences.':s.intro} breadcrumb={[{name:'Services',href:'/services'},{name:isSeo?'SEO + AI Search':s.name,href:'/services/'+s.slug}]}><PrimaryButton/><PrimaryButton href="#scope" secondary>Explore the approach</PrimaryButton></PageHero>
 <section className="section container split-section"><div><p className="eyebrow">The challenge</p><h2>{s.problemTitle}</h2></div><div className="prose"><p className="large-copy">{s.problem}</p><div className="outcome"><p className="eyebrow">The direction</p><p>{s.outcome}</p></div></div></section>
 <section id="scope" className="section contrast-section"><div className="container"><SectionHeader label="What we can help with" title={'THE RIGHT WORK.\nA CLEAR SCOPE.'} text="The exact deliverables, platforms, and integrations are agreed around your project."/><div className="scope-grid">{s.items.map(([h,p],i)=><article key={h}><span className="eyebrow">0{i+1}</span><h3>{h}</h3><p>{p}</p></article>)}</div><div className="considerations"><p className="eyebrow">Planning considerations</p><ul>{s.considerations.map(c=><li key={c}>{c}</li>)}</ul></div></div></section>
 {isSeo?<section className="section answer-engine-section"><div className="container"><SectionHeader label="Answer engine optimization" title={'SEARCH IS BECOMING\nMORE ANSWER-ORIENTED.'} text="The response is not to abandon SEO. It is to make useful, indexable content easier for search systems and people to understand."/><div className="answer-engine-grid"><article><p className="eyebrow">01 / Retrieval</p><h3>Make important pages easy to find.</h3><p>Crawlable HTML, descriptive internal links, a clean sitemap, useful service architecture, and technically sound pages remain the foundation.</p></article><article><p className="eyebrow">02 / Answers</p><h3>Lead with clarity.</h3><p>Directly answer recurring customer questions, then support the answer with context, limitations, process, and evidence that helps a serious prospect decide.</p></article><article><p className="eyebrow">03 / Entities</p><h3>Make the business unambiguous.</h3><p>Consistent names, services, market language, breadcrumbs, structured data, and connected pages help search systems understand what the business represents.</p></article><article><p className="eyebrow">04 / Credibility</p><h3>Use evidence you can verify.</h3><p>Actual work, accurate business facts, useful expertise, and sourced claims are stronger than fabricated statistics, awards, reviews, or AI-optimized filler.</p></article></div><div className="answer-engine-actions"><PrimaryButton href="/insights/answer-engine-optimization-local-business">Read the AEO guide</PrimaryButton><PrimaryButton href="/contact" secondary>Discuss your search strategy</PrimaryButton></div></div></section>:null}
 <section className="section dark"><div className="container split-section"><div><p className="eyebrow">Connected by design</p><h2>ONE SERVICE.<br/>PART OF A<br/>BIGGER PICTURE.</h2></div><div className="prose"><p className="large-copy">{s.connection}</p><div className="related-links">{services.filter(x=>x.slug!==slug).map(x=><Link key={x.slug} href={'/services/'+x.slug}>{x.name}<Arrow/></Link>)}</div></div></div></section>
 <section className="section container"><SectionHeader label="Built around your market" title={'SPECIFIC CUSTOMERS.\nSPECIFIC DECISIONS.'}/><div className="market-links"><Link href="/industries/real-estate"><h3>Real Estate</h3><p>Build confidence in your local expertise before the first conversation.</p><span className="text-link">Explore real estate marketing<Arrow/></span></Link><Link href="/industries/home-services"><h3>Home Services</h3><p>Make services clear, demonstrate quality, and help homeowners take the next step.</p><span className="text-link">Explore home service marketing<Arrow/></span></Link></div></section>
 <Process/><section className="section container"><SectionHeader label="Proof through work" title={'SEE THE FIRST\nIMPRESSION IN ACTION.'} text={slug==='web-design'?'Explore actual websites from our portfolio.':'Our website portfolio shows the digital experiences behind the wider acquisition journey.'}/><WorkGrid full selection={slug==='web-design'?projects:[projects[slug==='meta-ads'?1:0]]}/></section><FAQSection items={faqItems}/><CTA/>
 <JsonLd data={{'@context':'https://schema.org','@type':'Service',name:isSeo?'SEO & AI Search':s.name,description:serviceDescription,url:siteUrl+'/services/'+slug,provider:{'@type':'Organization','@id':siteUrl+'/#organization',name:'Digital Pathway',url:siteUrl},areaServed:'United States',audience:[{'@type':'BusinessAudience',audienceType:'Real estate businesses'},{'@type':'BusinessAudience',audienceType:'Home service businesses'}]}}/>
 </>;
}
