import Link from 'next/link';
import {notFound} from 'next/navigation';
import {services,projects,type FAQ} from '@/lib/content';
import {pageMetadata,siteUrl} from '@/lib/site';
import {PageHero,SectionHeader,PrimaryButton,WorkGrid,Process,FAQSection,CTA,JsonLd} from '@/components/shared';
import {Arrow} from '@/components/interactive';
export function generateStaticParams(){return services.map(s=>({slug:s.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=services.find(s=>s.slug===slug);if(!s)notFound();return pageMetadata(s.name+' for Real Estate & Home Services',s.intro,'/services/'+slug);}
export default async function Service({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const s=services.find(s=>s.slug===slug);if(!s)notFound();
 return <><PageHero label={s.name} title={s.line} text={s.intro} breadcrumb={[{name:'Services',href:'/services'},{name:s.name,href:'/services/'+s.slug}]}><PrimaryButton/><PrimaryButton href="#scope" secondary>Explore the approach</PrimaryButton></PageHero>
 <section className="section container split-section"><div><p className="eyebrow">The challenge</p><h2>{s.problemTitle}</h2></div><div className="prose"><p className="large-copy">{s.problem}</p><div className="outcome"><p className="eyebrow">The direction</p><p>{s.outcome}</p></div></div></section>
 <section id="scope" className="section contrast-section"><div className="container"><SectionHeader label="What we can help with" title={'THE RIGHT WORK.\nA CLEAR SCOPE.'} text="The exact deliverables, platforms, and integrations are agreed around your project."/><div className="scope-grid">{s.items.map(([h,p],i)=><article key={h}><span className="eyebrow">0{i+1}</span><h3>{h}</h3><p>{p}</p></article>)}</div><div className="considerations"><p className="eyebrow">Planning considerations</p><ul>{s.considerations.map(c=><li key={c}>{c}</li>)}</ul></div></div></section>
 <section className="section dark"><div className="container split-section"><div><p className="eyebrow">Connected by design</p><h2>ONE SERVICE.<br/>PART OF A<br/>BIGGER PICTURE.</h2></div><div className="prose"><p className="large-copy">{s.connection}</p><div className="related-links">{services.filter(x=>x.slug!==slug).map(x=><Link key={x.slug} href={'/services/'+x.slug}>{x.name}<Arrow/></Link>)}</div></div></div></section>
 <section className="section container"><SectionHeader label="Built around your market" title={'SPECIFIC CUSTOMERS.\nSPECIFIC DECISIONS.'}/><div className="market-links"><Link href="/industries/real-estate"><h3>Real Estate</h3><p>Build confidence in your local expertise before the first conversation.</p><span className="text-link">Explore real estate marketing<Arrow/></span></Link><Link href="/industries/home-services"><h3>Home Services</h3><p>Make services clear, demonstrate quality, and help homeowners take the next step.</p><span className="text-link">Explore home service marketing<Arrow/></span></Link></div></section>
 <Process/><section className="section container"><SectionHeader label="Proof through work" title={'SEE THE FIRST\nIMPRESSION IN ACTION.'} text={slug==='web-design'?'Explore actual websites from our portfolio.':'Our website portfolio shows the digital experiences behind the wider acquisition journey.'}/><WorkGrid full selection={slug==='web-design'?projects:[projects[slug==='meta-ads'?1:0]]}/></section><FAQSection items={s.faqs as FAQ[]}/><CTA/>
 <JsonLd data={{'@context':'https://schema.org','@type':'Service',name:s.name,description:s.intro,url:siteUrl+'/services/'+slug,provider:{'@type':'Organization',name:'Digital Pathway',url:siteUrl}}}/></>;
}
