import {PageHero,PrimaryButton,SectionHeader,FAQSection,CTA} from '@/components/shared';
import {pageMetadata} from '@/lib/site';
export const metadata=pageMetadata('Course, Coaching & Info Product Marketing','Marketing for real estate and home-service experts selling courses, coaching, and memberships. Connect offer positioning, funnels, paid ads, and follow-up.','/info-products');
const steps=[['Position','Create the offer and message.','Define who the program helps, what it teaches, and why it deserves their attention.'],['Attract','Build the acquisition path.','Connect relevant audiences to your offer through paid acquisition and clear positioning.'],['Convert','Give interest a next step.','Build funnels, landing pages, webinars, or applications around registration and enrollment.'],['Follow up','Continue the conversation.','Structure the journey after the first interaction so interested prospects have a reason to return.'],['Measure','Understand the path to enrollment.','Define relevant conversion events and connect performance with the quality of the people entering your offer.']];
export default function Info(){return <><PageHero label="A separate offering / For industry experts" title={'YOUR EXPERTISE.\nA BUSINESS\nAROUND IT.'} text="For real estate and home-service experts building courses, coaching, memberships, education products, and knowledge-based offers." breadcrumb={[{name:'Info Products',href:'/info-products'}]}><PrimaryButton href="/contact?service=info-products">Start an Info Product Project</PrimaryButton></PageHero>
 <section className="section container split-section"><div><p className="eyebrow">You bring the expertise</p><h2>KNOWING IT<br/>AND SELLING IT<br/>ARE DIFFERENT SKILLS.</h2></div><div className="prose"><p className="large-copy">Your experience is the foundation. A clear offer and a deliberate acquisition path help the right people understand why they should learn from you.</p><p>We partner with coaches, consultants, educators, experts, and creators in real estate and home services. You deliver the learning experience. We help connect the offer, message, funnel, and acquisition strategy.</p><div className="audience-tags">{['Coaches','Consultants','Educators','Experts','Creators'].map(a=><span key={a}>{a}</span>)}</div></div></section>
 <section className="section dark"><div className="container"><SectionHeader label="The education offer system" title={'FROM WHAT YOU KNOW\nTO WHO YOU CAN HELP.'}/><div className="info-system">{steps.map(([h,s,p],i)=><article key={h}><span className="eyebrow">0{i+1}</span><h3>{h}</h3><div><h4>{s}</h4><p>{p}</p></div></article>)}</div></div></section>
 <section className="section contrast-section"><div className="container"><SectionHeader label="Your offer sets the path" title={'A COURSE IS NOT A CALL.\nA MEMBER IS NOT A LEAD.'} text="The right funnel depends on what someone is deciding to buy."/><div className="scope-grid">{[
 ['Courses & education products','Prospective students need to understand what they will learn, who the material is for, and what is expected of them. The sales page should make those details clear before asking for enrollment.'],
 ['Coaching & consulting','A higher-consideration offer may need an application or conversation. Position the expertise clearly and help both sides understand whether the relationship is a fit.'],
 ['Memberships','Explain the ongoing value and who the community or resources are designed to help. Acquisition should reflect the real experience members will receive.'],
 ['Webinars & follow-up','A registration is one step. Connect the invitation, teaching topic, offer, and follow-up so interested people can evaluate whether to continue.'],
 ].map(([h,p])=><article key={h}><h3>{h}</h3><p>{p}</p></article>)}</div></div></section>
 <section className="section container split-section"><div><p className="eyebrow">A different conversion goal</p><h2>BUILT FOR<br/>ENROLLMENT.</h2></div><div className="prose"><p className="large-copy">Local-service marketing earns calls, quotes, and appointments. An education offer needs a path to registration, application, or enrollment.</p><p>That difference changes the message, the funnel, and the follow-up. This work stays separate from our core local-business offering so the strategy follows the right decision.</p><PrimaryButton href="/contact?service=info-products">Start an Info Product Project</PrimaryButton></div></section>
 <FAQSection title={'INFO PRODUCT\nMARKETING FAQ'} intro="Questions about your offer, audience, and path to enrollment." items={[['Who is the right fit?','Coaches, consultants, educators, experts, and creators whose knowledge is connected to real estate or home services.'],['What types of offers do you help market?','Courses, coaching, memberships, and other information products. The offer, audience, and responsibilities are agreed for each engagement.'],['Can you help if the course is not selling yet?','We can review the intended learner, offer, message, and acquisition path. If those foundations are unclear, buying more traffic is unlikely to answer the underlying question. The first scope should address what needs to be learned or improved.'],['Do you help with webinars and follow-up?','Yes. Webinar registration, education, and follow-up journeys are part of the capabilities we can scope around an offer.'],['Who delivers the education or coaching?','You bring the expertise and deliver the learning experience. Our role is the marketing strategy and acquisition path agreed in the engagement.'],['Do you guarantee enrollment or revenue?','No. There are no enrollment or revenue guarantees published here. The offer, audience, budget, experience, and execution all influence results.']]}/>
 <CTA title={'GIVE YOUR EXPERTISE\nA PATH FORWARD.'} text="Tell us what you teach, who it helps, and where you want to take it." href="/contact?service=info-products" label="Start an Info Product Project"/></>;}
